-- =============================================================================
-- Esquema relacional derivado del ERD (docs/ERD.md)
-- Motor objetivo: PostgreSQL 14+
-- Convenciones: snake_case, tipos acordes a 3FN, índices en FKs y consultas frecuentes
--
-- Notas de diseño:
-- - La entidad POSITION del diagrama se materializa como tabla "positions" para evitar
--   el identificador reservado POSITION en SQL.
-- - Longitudes VARCHAR no figuran en el ERD; se fijan según uso habitual (ajustables).
-- =============================================================================

BEGIN;

-- -----------------------------------------------------------------------------
-- company
-- -----------------------------------------------------------------------------
CREATE TABLE companies (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(255) NOT NULL
);

CREATE INDEX idx_companies_name ON companies (name);

-- -----------------------------------------------------------------------------
-- interview_flow (plantillas de proceso de entrevista)
-- -----------------------------------------------------------------------------
CREATE TABLE interview_flows (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description TEXT NOT NULL
);

-- -----------------------------------------------------------------------------
-- interview_type
-- -----------------------------------------------------------------------------
CREATE TABLE interview_types (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(120) NOT NULL,
    description TEXT
);

CREATE UNIQUE INDEX uq_interview_types_name ON interview_types (name);

-- -----------------------------------------------------------------------------
-- interview_step
-- -----------------------------------------------------------------------------
CREATE TABLE interview_steps (
    id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    interview_flow_id  INTEGER NOT NULL,
    interview_type_id  INTEGER NOT NULL,
    name               VARCHAR(255) NOT NULL,
    order_index        INTEGER NOT NULL,
    CONSTRAINT fk_interview_steps_flow
        FOREIGN KEY (interview_flow_id) REFERENCES interview_flows (id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_interview_steps_type
        FOREIGN KEY (interview_type_id) REFERENCES interview_types (id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT chk_interview_steps_order_non_negative
        CHECK (order_index >= 0)
);

CREATE INDEX idx_interview_steps_flow ON interview_steps (interview_flow_id);
CREATE INDEX idx_interview_steps_flow_order ON interview_steps (interview_flow_id, order_index);

-- -----------------------------------------------------------------------------
-- positions (entidad POSITION del ERD; ofertas de empleo por compañía)
-- -----------------------------------------------------------------------------
CREATE TABLE positions (
    id                   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id           INTEGER NOT NULL,
    interview_flow_id    INTEGER NOT NULL,
    title                VARCHAR(255) NOT NULL,
    description          TEXT,
    status               VARCHAR(50) NOT NULL,
    is_visible           BOOLEAN NOT NULL DEFAULT TRUE,
    location             VARCHAR(255),
    job_description      TEXT,
    requirements         TEXT,
    responsibilities     TEXT,
    salary_min           NUMERIC(12, 2),
    salary_max           NUMERIC(12, 2),
    employment_type      VARCHAR(80),
    benefits             TEXT,
    company_description  TEXT,
    application_deadline DATE,
    contact_info         VARCHAR(500),
    CONSTRAINT fk_positions_company
        FOREIGN KEY (company_id) REFERENCES companies (id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_positions_interview_flow
        FOREIGN KEY (interview_flow_id) REFERENCES interview_flows (id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT chk_positions_salary_range
        CHECK (
            salary_min IS NULL
            OR salary_max IS NULL
            OR salary_min <= salary_max
        )
);

CREATE INDEX idx_positions_company ON positions (company_id);
CREATE INDEX idx_positions_flow ON positions (interview_flow_id);
CREATE INDEX idx_positions_status ON positions (status);
CREATE INDEX idx_positions_deadline ON positions (application_deadline);

-- -----------------------------------------------------------------------------
-- employee
-- -----------------------------------------------------------------------------
CREATE TABLE employees (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id  INTEGER NOT NULL,
    name        VARCHAR(255) NOT NULL,
    email       VARCHAR(255) NOT NULL,
    role        VARCHAR(100) NOT NULL,
    is_active   BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT fk_employees_company
        FOREIGN KEY (company_id) REFERENCES companies (id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT uq_employees_company_email
        UNIQUE (company_id, email)
);

CREATE INDEX idx_employees_company ON employees (company_id);
CREATE INDEX idx_employees_active ON employees (company_id, is_active) WHERE is_active = TRUE;

-- -----------------------------------------------------------------------------
-- candidate
-- -----------------------------------------------------------------------------
CREATE TABLE candidates (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(100) NOT NULL,
    last_name  VARCHAR(100) NOT NULL,
    email      VARCHAR(255) NOT NULL,
    phone      VARCHAR(32),
    address    VARCHAR(500),
    CONSTRAINT uq_candidates_email UNIQUE (email)
);

CREATE INDEX idx_candidates_name ON candidates (last_name, first_name);

-- -----------------------------------------------------------------------------
-- application (candidatura de un candidato a una posición)
-- -----------------------------------------------------------------------------
CREATE TABLE applications (
    id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    position_id       INTEGER NOT NULL,
    candidate_id      INTEGER NOT NULL,
    application_date  DATE NOT NULL DEFAULT (CURRENT_DATE),
    status            VARCHAR(50) NOT NULL,
    notes             TEXT,
    CONSTRAINT fk_applications_position
        FOREIGN KEY (position_id) REFERENCES positions (id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_applications_candidate
        FOREIGN KEY (candidate_id) REFERENCES candidates (id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT uq_applications_position_candidate
        UNIQUE (position_id, candidate_id)
);

CREATE INDEX idx_applications_position ON applications (position_id);
CREATE INDEX idx_applications_candidate ON applications (candidate_id);
CREATE INDEX idx_applications_status ON applications (status);
CREATE INDEX idx_applications_date ON applications (application_date);

-- -----------------------------------------------------------------------------
-- interview (instancia de paso de entrevista para una candidatura)
-- -----------------------------------------------------------------------------
CREATE TABLE interviews (
    id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id     INTEGER NOT NULL,
    interview_step_id  INTEGER NOT NULL,
    employee_id        INTEGER NOT NULL,
    interview_date     DATE NOT NULL,
    result             VARCHAR(80),
    score              INTEGER,
    notes              TEXT,
    CONSTRAINT fk_interviews_application
        FOREIGN KEY (application_id) REFERENCES applications (id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_interviews_step
        FOREIGN KEY (interview_step_id) REFERENCES interview_steps (id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_interviews_employee
        FOREIGN KEY (employee_id) REFERENCES employees (id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT uq_interviews_application_step
        UNIQUE (application_id, interview_step_id),
    CONSTRAINT chk_interviews_score
        CHECK (score IS NULL OR (score >= 0 AND score <= 100))
);

CREATE INDEX idx_interviews_application ON interviews (application_id);
CREATE INDEX idx_interviews_step ON interviews (interview_step_id);
CREATE INDEX idx_interviews_employee ON interviews (employee_id);
CREATE INDEX idx_interviews_date ON interviews (interview_date);

COMMIT;

-- =============================================================================
-- Fin del script
-- =============================================================================
